export const FETCH_PODCASTS_REQUEST = "FETCH_PODCASTS_REQUEST";
export const FETCH_PODCASTS_SUCCESS = "FETCH_PODCASTS_SUCCESS";
export const FETCH_PODCASTS_FAILURE = "FETCH_PODCASTS_FAILURE";

export const FETCH_PODCAST_DETAIL_REQUEST = "FETCH_PODCAST_DETAIL_REQUEST";
export const FETCH_PODCAST_DETAIL_SUCCESS = "FETCH_PODCAST_DETAIL_SUCCESS";
export const FETCH_PODCAST_DETAIL_FAILURE = "FETCH_PODCAST_DETAIL_FAILURE";

export const FETCH_EPISODE_DETAIL_REQUEST = "FETCH_EPISODE_DETAIL_REQUEST";
export const FETCH_EPISODE_DETAIL_SUCCESS = "FETCH_EPISODE_DETAIL_SUCCESS";
export const FETCH_EPISODE_DETAIL_FAILURE = "FETCH_EPISODE_DETAIL_FAILURE";

export const SET_SELECTED_PODCAST = "SET_SELECTED_PODCAST";
